# Generated by Django 5.2 on 2025-05-19 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoapp', '0003_indexanalysis_eo_data'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eodata',
            unique_together={('satellite_image', 'index_type')},
        ),
    ]
