# Generated by Django 5.2 on 2025-05-24 21:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoapp', '0004_alter_eodata_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iotdata',
            name='data_type',
        ),
        migrations.RemoveField(
            model_name='iotdata',
            name='device_id',
        ),
        migrations.RemoveField(
            model_name='iotdata',
            name='device_name',
        ),
        migrations.RemoveField(
            model_name='iotdata',
            name='region',
        ),
        migrations.RemoveField(
            model_name='iotdata',
            name='value',
        ),
        migrations.AddField(
            model_name='iotdata',
            name='amg_avg_temp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='iotdata',
            name='amg_max_temp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='iotdata',
            name='amg_min_temp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='iotdata',
            name='bme_gas',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='iotdata',
            name='bme_humidity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='iotdata',
            name='bme_pressure',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='iotdata',
            name='bme_temp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='iotdata',
            name='luminosity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='iotdata',
            name='soil_moisture',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='iotdata',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Cartographical',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('geometry', models.JSONField(blank=True, null=True)),
                ('acquisition_date', models.DateField(blank=True, null=True)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cartographicals', to='geoapp.region')),
            ],
        ),
    ]
